version: "3"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_BASE}/prowlarr:/config
    ports:
      - ${PROWLARR_PORT}:9696
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_BASE}/radarr:/config
      - ${MEDIA_STORAGE_PATH}/media:/media
      - ${MEDIA_STORAGE_PATH}/media2:/media2
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - ${RADARR_PORT}:7878
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${VOLUME_BASE}/sonarr:/config
      - ${MEDIA_STORAGE_PATH}/media:/media
      - ${MEDIA_STORAGE_PATH}/media2:/media2
      - ${DOWNLOAD_PATH}:/downloads
    ports:
      - 8989:8989
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - ${JELLYSERR_PORT}:5055
    volumes:
      - ${VOLUME_BASE}/jellyseerr/config:/app/config
    restart: unless-stopped

  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    restart: unless-stopped
    volumes:
      - ${VOLUME_BASE}/chinesesubfinder:/config
      - ${MEDIA_STORAGE_PATH}/media2:/data/tvshows
      - ${MEDIA_STORAGE_PATH}/media:/data/movies
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PublishedServerUrl} #optional
    volumes:
      - ${VOLUME_BASE}/jellyfin/config:/config
      - ${MEDIA_STORAGE_PATH}/media2:/data/tvshows
      - ${MEDIA_STORAGE_PATH}/media:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - USER=${USER}
      - PASS=${PASSWORD}
    volumes:
      - ${VOLUME_BASE}/transmission:/config
      - ${DOWNLOAD_PATH}:/downloads/downloads
      - ${MEDIA_STORAGE_PATH}/watch:/watch
    ports:
      - ${TRANSMISSION_PORT}:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
